version: '3'
services:
    jsas:
        image: openjdk:16
        container_name: "jsas"
        hostname: "jsas"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/jsas
        environment:
            - JSAS_DIR=/var/jsas
            - JSAS_LOGGING=trace
        working_dir: /var/jsas
        command: java -jar jsas.jar
        restart: always

    nginx:
        image: "nginx"
        container_name: "nginx"
        hostname: "nginx"
        ports:
            - "82:82"
            - "443:443"
        volumes:
            - ".:/etc/nginx/certs"
            - ".:/var/log/nginx"
            - ".:/etc/nginx/conf.d"
